services:

  environment-model:
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/understanding/environment_model:latest
    volumes:
      - ./environment_model/params.yaml:/docker-ros/ws/install/environment_model/share/environment_model/config/params.yaml
    extends:
      file: ../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
  
  trajectory-suggestion:
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/planning/trajectory_suggestion:latest
    command: ros2 launch trajectory_suggestion trajectory_suggestion.launch.py input_topic:=/environment_model/rgb_bev_image
    extends:
      file: ../docker-compose-essentials/docker-compose.template.yaml
      service: ros2-gpu-service

  trajectory-supervision:
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/planning/trajectory_supervision:latest
    command: ros2 launch trajectory_supervision trajectory_supervision.launch.py input_topic:=/trajectory_suggestion_node/output_topic
    extends:
      file: ../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service