services:

  perception.point-cloud-ground-filter:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/perception/autoware_ground_filter:latest
    environment:
      NAMESPACE: /perception
      NAME: point-cloud-ground-filter
      INPUT_POINT_CLOUD_TOPIC: /perception/point_cloud_fusion/points
      OBSTACLE_POINT_CLOUD_TOPIC: /perception/point_cloud_fusion/points/obstacle
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch autoware_ground_filter ground_filter.launch.py \
          input/pointcloud:=$${INPUT_POINT_CLOUD_TOPIC} \
          output/pointcloud:=$${OBSTACLE_POINT_CLOUD_TOPIC}
    # volumes:
    #   - ./crop_box_filter_node.param.yaml:/docker-ros/ws/install/autoware_crop_box_filter/share/autoware_crop_box_filter/config/crop_box_filter_node.param.yaml
    #   - ./vehicle_info.param.yaml:/docker-ros/ws/install/autoware_vehicle_info_utils/share/autoware_vehicle_info_utils/config/vehicle_info.param.yaml
    #   - ./ground_filter.param.yaml:/docker-ros/ws/install/autoware_ground_filter/share/autoware_ground_filter/config/ground_filter.param.yaml

  perception.point-cloud-grid-mapping:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-gpu-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/perception/autoware_probabilistic_occupancy_grid_map:latest
    environment:
      NAMESPACE: /perception
      NAME: point-cloud-grid-mapping
      RAW_POINT_CLOUD_TOPIC: /perception/point_cloud_fusion/points
      OBSTACLE_POINT_CLOUD_TOPIC: /perception/point_cloud_fusion/points/obstacle
      OUTPUT_OCCUPANCY_GRID_TOPIC: /perception/point_cloud_grid_mapping/occupancy_grid
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch autoware_probabilistic_occupancy_grid_map pointcloud_based_occupancy_grid_map.launch.py \
          input/raw_pointcloud:=$${RAW_POINT_CLOUD_TOPIC} \
          input/obstacle_pointcloud:=$${OBSTACLE_POINT_CLOUD_TOPIC} \
          output:=$${OUTPUT_OCCUPANCY_GRID_TOPIC}
    # volumes:
    #   - ./pointcloud_based_occupancy_grid_map.param.yaml:/docker-ros/ws/install/autoware_probabilistic_occupancy_grid_map/share/autoware_probabilistic_occupancy_grid_map/config/pointcloud_based_occupancy_grid_map.param.yaml
    #   - ./binary_bayes_filter_updater.param.yaml:/docker-ros/ws/install/autoware_probabilistic_occupancy_grid_map/share/autoware_probabilistic_occupancy_grid_map/config/binary_bayes_filter_updater.param.yaml
