services:

  control.dbw-supervisor:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/control/dbw_supervisor:latest_init_ci
    environment:
      NAMESPACE: /control
      NAME: dbw_supervisor
      ACKERMANN_INPUT_TOPIC: /control/ackermann_cmd_supervised
      ACKERMANN_OUTPUT_TOPIC: /control/ackermann_cmd
      EMERGENCY_STOP_REQUESTED_TOPIC: /control/automated_emergency_braking/emergency_stop_requested
      ENABLE_HAZARD_LIGHTS_SERVICE: /drivers/fka_dbw/hazard_lights
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch dbw_supervisor dbw_supervisor_launch.py \
          namespace:=${NAMESPACE} \
          name:=${NAME} \
          ackermann_input_topic:=${ACKERMANN_INPUT_TOPIC} \
          ackermann_output_topic:=${ACKERMANN_OUTPUT_TOPIC} \
          emergency_stop_requested_topic:=${EMERGENCY_STOP_REQUESTED_TOPIC} \
          enable_hazard_lights_service:=${ENABLE_HAZARD_LIGHTS_SERVICE}
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/dbw_supervisor/share/dbw_supervisor/config/params.yml
