services:

  control.dbw-supervisor:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/control/dbw_supervisor:latest_init_ci
    environment:
      NAMESPACE: /control
      NAME: dbw_supervisor
      INPUT_TOPIC: /control/ackermann_cmd_supervised
      OUTPUT_TOPIC: /control/ackermann_cmd
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch dbw_supervisor dbw_supervisor_launch.xml \
          namespace:=$${NAMESPACE} \
          name:=$${NAME} \
          input_topic:=$${INPUT_TOPIC} \
          output_topic:=$${OUTPUT_TOPIC}
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/dbw_supervisor/share/dbw_supervisor/config/params.yml
