services:

  communication.etsi-its-conversion:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/definitions/etsi_its_messages:latest
    command: ros2 launch etsi_its_conversion converter.launch.py
