stages:
  - Downstream

# ==== Downstream ==============================================================

# --- fb-fi/its-modules/communication ---------------------------------------------------------------

ad2etsi:
  stage: Downstream
  only:
    - web
  allow_failure: true
  trigger:
    project: fb-fi/definitions/ad2etsi

etsi-its-messages:
  stage: Downstream
  only:
    - web
  allow_failure: true
  trigger:
    project: fb-fi/definitions/etsi_its_messages

etsi-its-v2x-generation:
  stage: Downstream
  only:
    - web
  allow_failure: true
  trigger:
    project: fb-fi/its-modules/communication/etsi_its_v2x_generation

mqtt-client-interfaces:
  stage: Downstream
  only:
    - web
  allow_failure: true
  trigger:
    project: fb-fi/its-modules/communication/mqtt-client-interfaces

transport-drivers:
  stage: Downstream
  only:
    - web
  allow_failure: true
  trigger:
    project: fb-fi/its-modules/drivers/transport_drivers

# --- fb-fi/its-modules/localization ---------------------------------------------

ego-state-estimation:
  stage: Downstream
  only:
    - web
  allow_failure: true
  trigger:
    project: fb-fi/its-modules/localization/ego_state_estimation

lanelet2-map-server:
  stage: Downstream
  only:
    - web
  allow_failure: true
  trigger:
    project: fb-fi/its-modules/localization/lanelet2_map_server

# --- fb-fi/its-modules/perception ---------------------------------------------

point-cloud-object-detection:
  stage: Downstream
  only:
    - web
  allow_failure: true
  trigger:
    project: fb-fi/its-modules/perception/point_cloud_object_detection

traffic-light-detection:
  stage: Downstream
  only:
    - web
  allow_failure: true
  trigger:
    project: fb-fi/its-modules/perception/traffic_light_detection

# --- fb-fi/its-modules/planning -----------------------------------------------

lanelet2-route-planning:
  stage: Downstream
  only:
    - web
  allow_failure: true
  trigger:
    project: fb-fi/its-modules/planning/lanelet2_route_planning

simple-planner:
  stage: Downstream
  only:
    - web
  allow_failure: true
  trigger:
    project: fb-fi/its-modules/planning/simple_planner

trajectory-optimization:
  stage: Downstream
  only:
    - web
  allow_failure: true
  trigger:
    project: fb-fi/its-modules/planning/trajectory_optimization

# --- fb-fi/its-modules/understanding

dynamic-map-enrichment:
  stage: Downstream
  only:
    - web
  allow_failure: true
  trigger:
    project: fb-fi/its-modules/understanding/dynamic_map_enrichment

lanelet2-object-list-prediction:
  stage: Downstream
  only:
    - web
  allow_failure: true
  trigger:
    project: fb-fi/its-modules/understanding/lanelet2_object_list_prediction

object-fusion:
  stage: Downstream
  only:
    - web
  allow_failure: true
  trigger:
    project: fb-fi/its-modules/understanding/object_fusion