services:

  planning.behavior_planning:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/planning/behavior_planning:v1.0.0
    depends_on:
      triton-server:
        condition: service_healthy
    environment:
      NAMESPACE: /planning
      NAME: behavior_planning
      USE_SIM_TIME: false
      EGO_DATA_TOPIC: /localization/ego_data
      ROUTE_TOPIC: /understanding/enriched_route
      OBJECT_LIST_TOPIC: /understanding/predicted_object_list
      IMAGE_TOPIC: ~/image
      TRAJECTORY_TOPIC: /planning/reference_trajectory
      EGO_MARKER_TOPIC: ~/visualization/ego_marker
      OBJECT_MARKER_TOPIC: ~/visualization/object_marker
      ROUTE_MARKER_TOPIC: ~/visualization/route_marker
      INFERENCE_TIME_TOPIC: ~/inference_time
      X_INIT_TOPIC: ~/x_init
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch behavior_planning behavior_planning_launch.py \
          namespace:=$${NAMESPACE} \
          name:=$${NAME} \
          use_sim_time:=$${USE_SIM_TIME} \
          ego_data_topic:=$${EGO_DATA_TOPIC} \
          route_topic:=$${ROUTE_TOPIC} \
          object_list_topic:=$${OBJECT_LIST_TOPIC} \
          image_topic:=$${IMAGE_TOPIC} \
          trajectory_topic:=$${TRAJECTORY_TOPIC} \
          ego_marker_topic:=$${EGO_MARKER_TOPIC} \
          object_marker_topic:=$${OBJECT_MARKER_TOPIC} \
          route_marker_topic:=$${ROUTE_MARKER_TOPIC} \
          inference_time_topic:=$${INFERENCE_TIME_TOPIC} \
          x_init_topic:=$${X_INIT_TOPIC}
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/behavior_planning/share/behavior_planning/config/params.yml
