# === Environment Variables ====================================================
# - EGO_DATA_TOPIC
# - ROUTE_TOPIC
# - OBJECT_LIST_TOPIC
# - TRAJECTORY_TOPIC
# - PARAMS_YML
# - USE_SIM_TIME
# ==============================================================================

services:

  planning.behavior_planning:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/planning/behavior_planning:latest_feature-inputs-with-new-route-format_ci
    command: ros2 launch behavior_planning behavior_planning_launch.py ego_data_topic:=/simulation/ego_data route_topic:=/route_planning/enriched_route object_list_topic:=/simulation/object_list image_topic:=/carla/ego_vehicle/sensors/cameras/camera_f/image trajectory_topic:=/planning/reference_trajectory ObjectMarkerTopic:=/visualization/object_marker RouteMarkerTopic:=/visualization/route_marker
    volumes:
      - ${PARAMS_YML:-/dev/null:/dev/null}${PARAMS_YML:+:/docker-ros/ws/install/behavior_planning/share/behavior_planning/config/params.yml}
