services:

  planning.behavior_planning:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/planning/behavior_planning:v1.0.0
    depends_on:
      - triton-server
    environment:
      NAMESPACE: /planning
      NAME: behavior_planning
      USE_SIM_TIME: ${USE_SIM_TIME:-false}
      CAMERA_IMAGE_IN: ~/camera_image
      EGO_DATA_IN: /ego_data
      OBJECT_LIST_IN: /understanding/lanelet2_object_list_prediction/object_list
      ROUTE_IN: /understanding/dynamic_map_enrichment/route
      TRAJECTORY_OUT: ~/reference_trajectory
      INFERENCE_TIME_OUT: ~/inference_time
      EGO_MARKER_OUT: ~/visualization/ego_marker
      OBJECT_MARKER_OUT: ~/visualization/object_marker
      ROUTE_MARKER_OUT: ~/visualization/route_marker
      X_INIT_OUT: ~/x_init
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch behavior_planning behavior_planning_launch.py \
          namespace:=$${NAMESPACE} \
          name:=$${NAME} \
          use_sim_time:=$${USE_SIM_TIME} \
          image_topic:=$${CAMERA_IMAGE_IN} \
          ego_data_topic:=$${EGO_DATA_IN} \
          object_list_topic:=$${OBJECT_LIST_IN} \
          route_topic:=$${ROUTE_IN} \
          trajectory_topic:=$${TRAJECTORY_OUT} \
          inference_time_topic:=$${INFERENCE_TIME_OUT} \
          ego_marker_topic:=$${EGO_MARKER_OUT} \
          object_marker_topic:=$${OBJECT_MARKER_OUT} \
          route_marker_topic:=$${ROUTE_MARKER_OUT} \
          x_init_topic:=$${X_INIT_OUT}
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/behavior_planning/share/behavior_planning/config/params.yml
