services:

  communication.etsi-its-conversion-sender:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/definitions/etsi_its_messages:ros2-jazzy
    environment:
      CAM_TOPIC: /communication/sender/cam
      CPM_TOPIC: /communication/sender/cpm
      DENM_TOPIC: /communication/sender/denm
      MAPEM_TOPIC: /communication/sender/mapem
      MCM_TOPIC: /communication/sender/mcm
      SPATEM_TOPIC: /communication/sender/spatem
      VAM_TOPIC: /communication/sender/vam
      UDP_TOPIC: /communication/sender/udp
      USE_SIM_TIME: false
    command: >
      bash -ic "
      ros2 launch etsi_its_conversion converter.launch.py
      name:=etsi_its_conversion_sender
      namespace:=communication
      input_topic_cam:=$${CAM_TOPIC}
      input_topic_cpm_ts:=$${CPM_TOPIC}
      input_topic_denm:=$${DENM_TOPIC}
      input_topic_mapem_ts:=$${MAPEM_TOPIC}
      input_topic_mcm_uulm:=$${MCM_TOPIC}
      input_topic_spatem_ts:=$${SPATEM_TOPIC}
      input_topic_vam_ts:=$${VAM_TOPIC}
      output_topic_udp:=$${UDP_TOPIC}
      use_sim_time:=$${USE_SIM_TIME}
      "
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/etsi_its_conversion/share/etsi_its_conversion/config/params.yml
