services:

  communication.etsi-its-conversion:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: ghcr.io/ika-rwth-aachen/etsi_its_messages:v3.4.0
    environment:
      NAMESPACE: /communication
      NAME: etsi_its_conversion
      USE_SIM_TIME: ${USE_SIM_TIME:-false}
      # inputs
      UDP_IN_TOPIC: ~/udp/in
      CAM_IN_TOPIC: ~/cam/in
      CPM_TS_IN_TOPIC: ~/cpm_ts/in
      DENM_IN_TOPIC: ~/denm/in
      MAPEM_TS_IN_TOPIC: ~/mapem_ts/in
      MCM_UULM_IN_TOPIC: ~/mcm_uulm/in
      SPATEM_TS_IN_TOPIC: ~/spatem_ts/in
      VAM_TS_IN_TOPIC: ~/vam_ts/in
      # outputs
      UDP_OUT_TOPIC: ~/udp/out
      CAM_OUT_TOPIC: ~/cam/out
      CPM_TS_OUT_TOPIC: ~/cpm_ts/out
      DENM_OUT_TOPIC: ~/denm/out
      MAPEM_TS_OUT_TOPIC: ~/mapem_ts/out
      MCM_UULM_OUT_TOPIC: ~/mcm_uulm/out
      SPATEM_TS_OUT_TOPIC: ~/spatem_ts/out
      VAM_TS_OUT_TOPIC: ~/vam_ts/out
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch etsi_its_conversion converter.launch.py \
          namespace:=$${NAMESPACE} \
          name:=$${NAME} \
          use_sim_time:=$${USE_SIM_TIME} \
          input_topic_udp:=$${UDP_IN_TOPIC} \
          input_topic_cam:=$${CAM_IN_TOPIC} \
          input_topic_cpm_ts:=$${CPM_TS_IN_TOPIC} \
          input_topic_denm:=$${DENM_IN_TOPIC} \
          input_topic_mapem_ts:=$${MAPEM_TS_IN_TOPIC} \
          input_topic_mcm_uulm:=$${MCM_UULM_IN_TOPIC} \
          input_topic_spatem_ts:=$${SPATEM_TS_IN_TOPIC} \
          input_topic_vam_ts:=$${VAM_TS_IN_TOPIC} \
          output_topic_udp:=$${UDP_OUT_TOPIC} \
          output_topic_cam:=$${CAM_OUT_TOPIC} \
          output_topic_cpm_ts:=$${CPM_TS_OUT_TOPIC} \
          output_topic_denm:=$${DENM_OUT_TOPIC} \
          output_topic_mapem_ts:=$${MAPEM_TS_OUT_TOPIC} \
          output_topic_mcm_uulm:=$${MCM_UULM_OUT_TOPIC} \
          output_topic_spatem_ts:=$${SPATEM_TS_OUT_TOPIC} \
          output_topic_vam_ts:=$${VAM_TS_OUT_TOPIC}
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/etsi_its_conversion/share/etsi_its_conversion/config/params.yml