services:

  communication.etsi-its-conversion-receiver:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/definitions/etsi_its_messages:ros2-jazzy
    environment:
      NAMESPACE: /communication
      NAME: etsi_its_conversion_receiver
      USE_SIM_TIME: false
      INPUT_TOPIC_UDP: /communication/receiver/udp
      OUTPUT_TOPIC_CAM: /communication/receiver/cam
      OUTPUT_TOPIC_CPM_TS: /communication/receiver/cpm
      OUTPUT_TOPIC_DENM: /communication/receiver/denm
      OUTPUT_TOPIC_MAPEM_TS: /communication/receiver/mapem
      OUTPUT_TOPIC_MCM_UULM: /communication/receiver/mcm
      OUTPUT_TOPIC_SPATEM_TS: /communication/receiver/spatem
      OUTPUT_TOPIC_VAM_TS: /communication/receiver/vam
    command:
      - /bin/bash
      - -c
      - |
        ros2 launch etsi_its_conversion converter.launch.py \
          namespace:=$${NAMESPACE} \
          name:=$${NAME} \
          use_sim_time:=$${USE_SIM_TIME} \
          input_topic_udp:=$${INPUT_TOPIC_UDP} \
          output_topic_cam:=$${OUTPUT_TOPIC_CAM} \
          output_topic_cpm_ts:=$${OUTPUT_TOPIC_CPM_TS} \
          output_topic_denm:=$${OUTPUT_TOPIC_DENM} \
          output_topic_mapem_ts:=$${OUTPUT_TOPIC_MAPEM_TS} \
          output_topic_mcm_uulm:=$${OUTPUT_TOPIC_MCM_UULM} \
          output_topic_spatem_ts:=$${OUTPUT_TOPIC_SPATEM_TS} \
          output_topic_vam_ts:=$${OUTPUT_TOPIC_VAM_TS}
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/etsi_its_conversion/share/etsi_its_conversion/config/params.yml

  communication.etsi-its-conversion-sender:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/definitions/etsi_its_messages:ros2-jazzy
    environment:
      NAMESPACE: /communication
      NAME: etsi_its_conversion_sender
      USE_SIM_TIME: false
      INPUT_TOPIC_CAM: /communication/sender/cam
      INPUT_TOPIC_CPM_TS: /communication/sender/cpm
      INPUT_TOPIC_DENM: /communication/sender/denm
      INPUT_TOPIC_MAPEM_TS: /communication/sender/mapem
      INPUT_TOPIC_MCM_UULM: /communication/sender/mcm
      INPUT_TOPIC_SPATEM_TS: /communication/sender/spatem
      INPUT_TOPIC_VAM_TS: /communication/sender/vam
      OUTPUT_TOPIC_UDP: /communication/sender/udp
    command:
      - /bin/bash
      - -c
      - |
        ros2 launch etsi_its_conversion converter.launch.py \
          namespace:=$${NAMESPACE} \
          name:=$${NAME} \
          use_sim_time:=$${USE_SIM_TIME} \
          input_topic_cam:=$${INPUT_TOPIC_CAM} \
          input_topic_cpm_ts:=$${INPUT_TOPIC_CPM_TS} \
          input_topic_denm:=$${INPUT_TOPIC_DENM} \
          input_topic_mapem_ts:=$${INPUT_TOPIC_MAPEM_TS} \
          input_topic_mcm_uulm:=$${INPUT_TOPIC_MCM_UULM} \
          input_topic_spatem_ts:=$${INPUT_TOPIC_SPATEM_TS} \
          input_topic_vam_ts:=$${INPUT_TOPIC_VAM_TS} \
          output_topic_udp:=$${OUTPUT_TOPIC_UDP}
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/etsi_its_conversion/share/etsi_its_conversion/config/params.yml
