services:

  communication.etsi-its-conversion-receiver:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: ghcr.io/ika-rwth-aachen/etsi_its_messages:latest
    environment:
      NAMESPACE: /communication
      NAME: etsi_its_conversion_receiver
      USE_SIM_TIME: false
      INPUT_TOPIC_UDP: ~/udp/in
      OUTPUT_TOPIC_CAM: ~/cam/out
      OUTPUT_TOPIC_CPM_TS: ~/cpm_ts/out
      OUTPUT_TOPIC_DENM: ~/denm/out
      OUTPUT_TOPIC_MAPEM_TS: ~/mapem_ts/out
      OUTPUT_TOPIC_MCM_UULM: ~/mcm_uulm/out
      OUTPUT_TOPIC_SPATEM_TS: ~/spatem_ts/out
      OUTPUT_TOPIC_VAM_TS: ~/vam/out
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch etsi_its_conversion converter.launch.py \
          namespace:=$${NAMESPACE} \
          name:=$${NAME} \
          use_sim_time:=$${USE_SIM_TIME} \
          input_topic_udp:=$${INPUT_TOPIC_UDP} \
          output_topic_cam:=$${OUTPUT_TOPIC_CAM} \
          output_topic_cpm_ts:=$${OUTPUT_TOPIC_CPM_TS} \
          output_topic_denm:=$${OUTPUT_TOPIC_DENM} \
          output_topic_mapem_ts:=$${OUTPUT_TOPIC_MAPEM_TS} \
          output_topic_mcm_uulm:=$${OUTPUT_TOPIC_MCM_UULM} \
          output_topic_spatem_ts:=$${OUTPUT_TOPIC_SPATEM_TS} \
          output_topic_vam_ts:=$${OUTPUT_TOPIC_VAM_TS}
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/etsi_its_conversion/share/etsi_its_conversion/config/params.yml

  communication.etsi-its-conversion-sender:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: ghcr.io/ika-rwth-aachen/etsi_its_messages:latest
    environment:
      NAMESPACE: /communication
      NAME: etsi_its_conversion_sender
      USE_SIM_TIME: false
      INPUT_TOPIC_CAM: ~/cam/in
      INPUT_TOPIC_CPM_TS: ~/cpm_ts/in
      INPUT_TOPIC_DENM: ~/denm/in
      INPUT_TOPIC_MAPEM_TS: ~/mapem_ts/in
      INPUT_TOPIC_MCM_UULM: ~/mcm_uulm/in
      INPUT_TOPIC_SPATEM_TS: ~/spatem_ts/in
      INPUT_TOPIC_VAM_TS: ~/vam/in
      OUTPUT_TOPIC_UDP: ~/udp/out
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch etsi_its_conversion converter.launch.py \
          namespace:=$${NAMESPACE} \
          name:=$${NAME} \
          use_sim_time:=$${USE_SIM_TIME} \
          input_topic_cam:=$${INPUT_TOPIC_CAM} \
          input_topic_cpm_ts:=$${INPUT_TOPIC_CPM_TS} \
          input_topic_denm:=$${INPUT_TOPIC_DENM} \
          input_topic_mapem_ts:=$${INPUT_TOPIC_MAPEM_TS} \
          input_topic_mcm_uulm:=$${INPUT_TOPIC_MCM_UULM} \
          input_topic_spatem_ts:=$${INPUT_TOPIC_SPATEM_TS} \
          input_topic_vam_ts:=$${INPUT_TOPIC_VAM_TS} \
          output_topic_udp:=$${OUTPUT_TOPIC_UDP}
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/etsi_its_conversion/share/etsi_its_conversion/config/params.yml
