# === Environment Variables ====================================================
# - EGO_DATA_TOPIC
# - USE_SIM_TIME
# - PARAMS_YML
# ==============================================================================

services:

  mission-planning.route-planning:
    extends:
      file: ../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/planning/lanelet2_route_planning:latest
    command: ros2 launch lanelet2_route_planning ll2_route_planning.launch.py ego_data_topic:=${EGO_DATA_TOPIC} use_sim_time_arg:=${USE_SIM_TIME:-false}
    volumes:
      - ${PARAMS_YML:-./config/params.route_planning.yml}:/docker-ros/ws/install/lanelet2_route_planning/share/lanelet2_route_planning/config/params.yml