# Remote compose file with overrides defined here can be rendered by
# `../../utils/scripts/render_compose_sources.py`

include:
  # https://github.com/openads-project/simple_planner/blob/TODO/docker/compose/docker-compose.yml
  - oci://ghcr.io/openads-project/simple_planner:compose-main

services:

  simple-planner:
    extends:
      file: ../../utils/compose/docker-compose.template.yml
      service: ros2-service
    image: ghcr.io/openads-project/simple_planner:latest
    environment:
      # --- name ------
      NAMESPACE: /planning
      # --- inputs ----
      EGO_DATA_TOPIC: /localization/ego_state_estimation/ego_data
      OBJECT_LIST_TOPIC: /understanding/lanelet2_object_list_prediction/object_list
      ROUTE_TOPIC: /planning/lanelet2_route_planning/route
