services:

  planning.simple-planner:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/planning/simple_planner:latest
    environment:
      NAMESPACE: /planning
      NAME: simple_planner
      USE_SIM_TIME: false
      EGO_DATA_TOPIC: /localization/ego_data
      ROUTE_TOPIC: /understanding/enriched_route
      TRAJECTORY_TOPIC: /planning/reference_trajectory
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch simple_planner simple_planner.launch.py \
          namespace:=$${NAMESPACE} \
          name:=$${NAME} \
          use_sim_time:=$${USE_SIM_TIME} \
          ego_data_topic:=$${EGO_DATA_TOPIC} \
          route_topic:=$${ROUTE_TOPIC} \
          trajectory_topic:=$${TRAJECTORY_TOPIC}
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/simple_planner/share/simple_planner/config/params.yml
