services:

  trace-compass:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-x11-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/misc/ros2-tracing-analysis:v1.0.3
    volumes:
      - .:/trace
    network_mode: host
