# === Environment Variables ====================================================
# - EGO_DATA_TOPIC(optional)
# - OBJECT_LIST_TOPIC(optional)
# - CAM_TOPIC     (optional)
# - CAM_UDP_TOPIC (optional)
# - CPM_TOPIC     (optional)
# - CPM_UDP_TOPIC (optional)
# - USE_SIM_TIME  (optional)
# - PARAMS_YML    (optional)
# ==============================================================================

services:

  communication.cam-etsi-its-v2x-generation:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/communication/etsi_its_v2x_generation:latest_cpm-generator_ci
    command: >
      ros2 launch etsi_its_v2x_generation cam_generator_launch.py
      namespace:=/communication
      ego_data_topic:=${EGO_DATA_TOPIC:-/localization/ego_data}
      cam_topic:=${CAM_TOPIC:-/communication/cam}
      udp_topic:=${CAM_UDP_TOPIC:-/communication/cam_udp}
      use_sim_time:=${USE_SIM_TIME:-false}
    volumes:
      - ${PARAMS_YML:-/dev/null:/dev/null}${PARAMS_YML:+:/docker-ros/ws/install/etsi_its_v2x_generation/share/etsi_its_v2x_generation/config/params.yml}

  communication.cpm-etsi-its-v2x-generation:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/communication/etsi_its_v2x_generation:latest_cpm-generator_ci
    command: >
      ros2 launch etsi_its_v2x_generation cpm_generator_launch.py
      namespace:=/communication
      object_list_topic:=${OBJECT_LIST_TOPIC:-/perception/object_list}
      cpm_topic:=${CPM_TOPIC:-/communication/cpm}
      udp_topic:=${CPM_UDP_TOPIC:-/communication/cpm_udp}
      use_sim_time:=${USE_SIM_TIME:-false}
    volumes:
      - ${PARAMS_YML:-/dev/null:/dev/null}${PARAMS_YML:+:/docker-ros/ws/install/etsi_its_v2x_generation/share/etsi_its_v2x_generation/config/params.yml}
