services:

  communication.etsi-its-v2x-generation.cam:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/communication/etsi_its_v2x_generation:v1.0.0
    environment:
      NAMESPACE: /communication
      NAME: etsi_its_v2x_generation_cam
      USE_SIM_TIME: ${USE_SIM_TIME:-false}
      # inputs
      EGO_DATA_TOPIC: /localization/ego_state_estimation/ego_data
      # outputs
      CAM_TOPIC: ~/cam
      UDP_TOPIC: ~/udp
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch etsi_its_v2x_generation cam_generator.launch.py \
          namespace:=$${NAMESPACE} \
          name:=$${NAME} \
          use_sim_time:=$${USE_SIM_TIME} \
          ego_data_topic:=$${EGO_DATA_TOPIC} \
          cam_topic:=$${CAM_TOPIC} \
          udp_topic:=$${UDP_TOPIC}
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/etsi_its_v2x_generation/share/etsi_its_v2x_generation/config/params.cam_generator.yml

  communication.etsi-its-v2x-generation.cpm:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/communication/etsi_its_v2x_generation:v1.0.0
    environment:
      NAMESPACE: /communication
      NAME: etsi_its_v2x_generation_cpm
      USE_SIM_TIME: ${USE_SIM_TIME:-false}
      # inputs
      OBJECT_LIST_TOPIC: /understanding/lanelet2_object_list_prediction/predicted_object_list
      # outputs
      CPM_TOPIC: ~/cpm
      UDP_TOPIC: ~/udp
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch etsi_its_v2x_generation cpm_generator.launch.py \
          namespace:=$${NAMESPACE} \
          name:=$${NAME} \
          use_sim_time:=$${USE_SIM_TIME} \
          object_list_topic:=$${OBJECT_LIST_TOPIC} \
          cpm_topic:=$${CPM_TOPIC} \
          udp_topic:=$${UDP_TOPIC}
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/etsi_its_v2x_generation/share/etsi_its_v2x_generation/config/params.cpm_generator.yml
