services:

  planning.lanelet2-route-planning:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/planning/lanelet2_route_planning:latest
    environment:
      NAMESPACE: /planning
      NAME: lanelet2_route_planning
      USE_SIM_TIME: false
      EGO_DATA_TOPIC: /localization/ego_data
      ROUTE_TOPIC: /planning/route
    command:
      - /bin/bash
      - -c
      - |
        ros2 launch lanelet2_route_planning lanelet2_route_planning_launch.py \
          namespace:=$${NAMESPACE} \
          name:=$${NAME} \
          use_sim_time:=$${USE_SIM_TIME} \
          ego_data_topic:=$${EGO_DATA_TOPIC} \
          route_topic:=$${ROUTE_TOPIC}
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/lanelet2_route_planning/share/lanelet2_route_planning/config/params.yml
