services:

  communication.ad2etsi:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/definitions/ad2etsi:latest
    environment:
      EGO_DATA_TOPIC: /localization/ego_data
      OBJECT_LIST_TOPIC: /understanding/predicted_object_list
      CAM_TOPIC: /communication/sender/cam
      CPM_TOPIC: /communication/sender/cpm
    command: >
      bash -ic "
      ros2 launch ad2etsi_converter_node ad2etsi_component_launch.py
      node_name:=ad2etsi_converter_node
      namespace:=communication
      ego_data_in:=$${EGO_DATA_TOPIC}
      object_list_in:=$${OBJECT_LIST_TOPIC}
      cam_out:=$${CAM_TOPIC}
      cpm_out:=$${CPM_TOPIC}
      "
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/ad2etsi_converter_node/share/ad2etsi_converter_node/config/params.yml
