services:

  communication.etsi2ad:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/definitions/ad2etsi:v1.0.0
    environment:
      NAMESPACE: /communication
      NAME: etsi2ad
      USE_SIM_TIME: ${USE_SIM_TIME:-false}
      # inputs
      CAM_TOPIC: /communication/etsi_its_conversion_receiver/cam
      CPM_TOPIC: /communication/etsi_its_conversion_receiver/cpm_ts
      # outputs
      EGO_DATA_TOPIC: ~/ego_data
      OBJECT_LIST_TOPIC: ~/object_list
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch ad2etsi_converter_node ad2etsi_component_launch.py \
          namespace:=$${NAMESPACE} \
          node_name:=$${NAME} \
          use_sim_time:=$${USE_SIM_TIME} \
          cam_in:=$${CAM_TOPIC} \
          cpm_in:=$${CPM_TOPIC} \
          ego_data_out:=$${EGO_DATA_TOPIC} \
          object_list_out:=$${OBJECT_LIST_TOPIC}
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/ad2etsi_converter_node/share/ad2etsi_converter_node/config/params.yml

  communication.ad2etsi:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/definitions/ad2etsi:v1.0.0
    environment:
      NAMESPACE: /communication
      NAME: ad2etsi
      USE_SIM_TIME: ${USE_SIM_TIME:-false}
      # inputs
      EGO_DATA_TOPIC: /localization/ego_state_estimation/localization/ego_state_estimation/localization/ego_state_estimation/localization/ego_state_estimation/localization/ego_state_estimation/localization/ego_state_estimation/localization/ego_state_estimation/ego_data
      OBJECT_LIST_TOPIC: /understanding/lanelet2_object_list_prediction/predicted_object_list
      # outputs
      CAM_TOPIC: ~/cam
      CPM_TOPIC: ~/cpm_ts
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch ad2etsi_converter_node ad2etsi_component_launch.py \
          namespace:=$${NAMESPACE} \
          node_name:=$${NAME} \
          use_sim_time:=$${USE_SIM_TIME} \
          ego_data_in:=$${EGO_DATA_TOPIC} \
          object_list_in:=$${OBJECT_LIST_TOPIC} \
          cam_out:=$${CAM_TOPIC} \
          cpm_out:=$${CPM_TOPIC}
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/ad2etsi_converter_node/share/ad2etsi_converter_node/config/params.yml
