# === Environment Variables ====================================================
# - PARAMS_YML (optional)
# ==============================================================================

services:

  understanding.environment-model:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/understanding/environment_model:latest_jazzy_ci
    volumes:
      - ${PARAMS_YML:-/dev/null:/dev/null}${PARAMS_YML:+:/docker-ros/ws/install/environment_model/share/environment_model/config/params.yaml}