# === Environment Variables ====================================================
# - PORT        (required)
# - IP          (required)
# - UDP_TOPIC   (optional)
# ==============================================================================

services:
  communication.udp-receiver:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/drivers/transport_drivers:latest
    command: ros2 run udp_driver udp_receiver_node_exe --ros-args -p ip:="${IP}" -p port:=${PORT} -r /udp_read:=${UDP_TOPIC:-/communication/receiver/udp}
    ports:
      - ${PORT}:${PORT}/udp