services:
  communication.udp-receiver:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/drivers/transport_drivers:latest
    environment:
      NAMESPACE: /communication
      NAME: udp_receiver
      IP: "0.0.0.0"
      PORT: 4400
      UDP_TOPIC: /communication/receiver/udp
      USE_SIM_TIME: false
      DOCKER_UID: "" # run as root
      DOCKER_GID: ""
    command:
      - /bin/bash
      - -c
      - |
        ros2 launch /docker-ros/additional-files/udp_receiver_node.launch.py \
          namespace:=$${NAMESPACE} \
          name:=$${NAME} \
          ip:=$${IP} \
          port:=$${PORT} \
          udp_topic:=$${UDP_TOPIC} \
          use_sim_time:=$${USE_SIM_TIME}
    # ports:
    #   - 4400:4400/udp

  communication.udp-sender:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/drivers/transport_drivers:latest
    environment:
      NAMESPACE: /communication
      NAME: udp_sender
      IP: "127.0.0.1"
      PORT: 4401
      UDP_TOPIC: /communication/sender/udp
      USE_SIM_TIME: false
      DOCKER_UID: "" # run as root
      DOCKER_GID: ""
    command:
      - /bin/bash
      - -c
      - |
        ros2 launch /docker-ros/additional-files/udp_sender_node.launch.py \
          namespace:=$${NAMESPACE} \
          name:=$${NAME} \
          ip:=$${IP} \
          port:=$${PORT} \
          udp_topic:=$${UDP_TOPIC} \
          use_sim_time:=$${USE_SIM_TIME}
