# === Environment Variables ====================================================
# - IMAGE
# - SEGMENTED_IMAGE
# - PARAMS_YML
# ==============================================================================

x-image-segmentation-base: &image-segmentation-base
  extends:
    file: ../../docker-compose-essentials/docker-compose.template.yml
    service: ros2-gpu-service
  image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/perception/image_segmentation:latest
  volumes:
    - ./launch/image_segmentation_launch.py:/docker-ros/ws/install/image_segmentation/share/image_segmentation/launch/image_segmentation_launch.py
    - ./models:/docker-ros/ws/install/image_segmentation/share/image_segmentation/models
    - ./one-hot-conversion:/docker-ros/ws/install/image_segmentation/share/image_segmentation/one-hot-conversion
    - ${PARAMS_YML:-./config/params.yml}:/docker-ros/ws/install/image_segmentation/share/image_segmentation/config/params.yaml

# ==============================================================================

services:

  perception.image-segmentation:
    <<: *image-segmentation-base
    command: ros2 launch image_segmentation image_segmentation_launch.py image:=${IMAGE} segmented_image:=${SEGMENTED_IMAGE}
