services:

  map-server:
    extends:
      file: ../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/localization/lanelet2_map_server:latest
    command: ros2 run lanelet2_map_server lanelet2_map_server --ros-args -p map_filepath:=/data/maps/ATC.osm -p origin_lat:=50.771611 -p origin_lon:=6.046402
    volumes:
      - map:/data/maps/

  map-provider-atc:
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/assets/locations/germany-aldenhoven-atc.lanelet2.ika-carla
    volumes:
      - map:/data/

  # map-provider-melaten:
  #   image: gitlab.ika.rwth-aachen.de:5050/fb-fi/assets/locations/germany-aachen-campusmelaten.lanelet2.ika-campus-vaals-halifax
  #   volumes:
  #     - map:/data

  # map-provider-town10hd:
  #   image: gitlab.ika.rwth-aachen.de:5050/fb-fi/assets/locations/synthetic-carla.lanelet2.town10hd
  #   volumes:
  #     - map:/data/

volumes:
  map:
