services:

  understanding.object-fusion:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/understanding/object_fusion:latest
    environment:
      NAMESPACE: /understanding
      NAME: object_fusion
      USE_SIM_TIME: false
      ROS_TRACING: false
      RAW_OBJECT_LISTS_TOPIC: ~/raw_object_lists
      FUSED_OBJECT_LIST_TOPIC: /understanding/fused_object_list
      FUSED_TRAJECTORIES_TOPIC: /understanding/fused_trajectories
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch object_fusion fusion_function_launch.py \
          namespace:=$${NAMESPACE} \
          node_name:=$${NAME} \
          use_sim_time:=$${USE_SIM_TIME} \
          trace:=$${ROS_TRACING} \
          raw_object_lists_topic:=$${RAW_OBJECT_LISTS_TOPIC} \
          fused_object_list_topic:=$${FUSED_OBJECT_LIST_TOPIC} \
          fused_trajectories_topic:=$${FUSED_TRAJECTORIES_TOPIC}
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/object_fusion/share/object_fusion/config/params.yml
