services:

  understanding.dynamic-map-enrichment:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/understanding/dynamic_map_enrichment:v1.0.0
    environment:
      NAMESPACE: /understanding
      NAME: dynamic_map_enrichment
      USE_SIM_TIME: ${USE_SIM_TIME:-false}
      MAPEM_IN: /communication/etsi_its_conversion_receiver/mapem_ts
      ROUTE_IN: /planning/lanelet2_route_planning/route
      SPATEM_IN: /communication/etsi_its_conversion_receiver/spatem_ts
      TRAFFIC_LIGHT_IN: /perception/traffic_light_detection/detections
      ENRICHED_ROUTE_OUT: ~/route
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch dynamic_map_enrichment dynamic_map_enrichment_node.launch.py \
          namespace:=$${NAMESPACE} \
          name:=$${NAME} \
          use_sim_time:=$${USE_SIM_TIME} \
          mapem_topic:=$${MAPEM_IN} \
          route_topic:=$${ROUTE_IN} \
          spatem_topic:=$${SPATEM_IN} \
          traffic_light_topic:=$${TRAFFIC_LIGHT_IN} \
          enriched_route_topic:=$${ENRICHED_ROUTE_OUT}
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/dynamic_map_enrichment/share/dynamic_map_enrichment/config/params.yml
