services:

  understanding.dynamic-map-enrichment:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/understanding/dynamic_map_enrichment:latest
    environment:
      NAMESPACE: /understanding
      NAME: dynamic_map_enrichment
      ROUTE_TOPIC: /lanelet2_route_planning/route
      MAPEM_TOPIC: /communication/receiver/mapem
      SPATEM_TOPIC: /communication/receiver/spatem
      TRAFFIC_LIGHT_TOPIC: /traffic_light_detection/cameras/tld_camera/data/tracking
      ENRICHED_ROUTE_TOPIC: /understanding/enriched_route
      USE_SIM_TIME: false
    command:
      - /bin/bash
      - -c
      - |
        ros2 launch dynamic_map_enrichment dynamic_map_enrichment_node.launch.py \
        namespace:=$${NAMESPACE} \
        name:=$${NAME} \
        route_topic:=$${ROUTE_TOPIC} \
        mapem_topic:=$${MAPEM_TOPIC} \
        spatem_topic:=$${SPATEM_TOPIC} \
        traffic_light_topic:=$${TRAFFIC_LIGHT_TOPIC} \
        enriched_route_topic:=$${ENRICHED_ROUTE_TOPIC} \
        use_sim_time:=$${USE_SIM_TIME}
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/dynamic_map_enrichment/share/dynamic_map_enrichment/config/params.yml
