services:

  understanding.dynamic-map-enrichment:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/understanding/dynamic_map_enrichment:latest
    environment:
      NAMESPACE: /understanding
      NAME: dynamic_map_enrichment
      USE_SIM_TIME: false
      ROUTE_TOPIC: /planning/route
      MAPEM_TOPIC: /communication/etsi_its_conversion_receiver/mapem_ts/out
      SPATEM_TOPIC: /communication/etsi_its_conversion_receiver/spatem_ts/out
      TRAFFIC_LIGHT_TOPIC: /perception/traffic_light_detection/output
      ENRICHED_ROUTE_TOPIC: /understanding/enriched_route
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch dynamic_map_enrichment dynamic_map_enrichment_node.launch.py \
          namespace:=$${NAMESPACE} \
          name:=$${NAME} \
          use_sim_time:=$${USE_SIM_TIME} \
          route_topic:=$${ROUTE_TOPIC} \
          mapem_topic:=$${MAPEM_TOPIC} \
          spatem_topic:=$${SPATEM_TOPIC} \
          traffic_light_topic:=$${TRAFFIC_LIGHT_TOPIC} \
          enriched_route_topic:=$${ENRICHED_ROUTE_TOPIC}
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/dynamic_map_enrichment/share/dynamic_map_enrichment/config/params.yml
