/**:
  ros__parameters:

    core_configuration:
      trigger_on: "Frequency"
      topic: "/carla_its_adapter/object_list/base_link" # TODO
      frequency: 20.0
      storing_time: 10.0

    output:      
      Example:
        enabled: False
        topic: "/environment_model/example"
        rate: 20.0
      
      RGB_BEV_Image:
        enabled: True
        topic: "/environment_model/rgb_bev_image"
        rate: 5.0
        width: 258
        height: 258
        center_offset: 0.25
        environment_width: 80.0 #m               
        environment_height: 80.0 #m
        history_time: 2.0 #s
        history_sampling_step: 0.25 #s

      Behavior_planning_images:
        enabled: False
        topic: "/environment_model/rgb_bev_image"
        topic_multilayer_image: "/environment_model/multilayer_image"
        rate: 5.0
        width: 224
        height: 224
        channels: 6
        environment_width: 50.0 #m               
        environment_height: 50.0 #m
        ego_pos_x: 112 #px
        ego_pos_y: 196 #px
        history_time: 1.0 #s
        past_poses_amount: 5
        stopline_width_factor: 0.2 # factor for deriving the width from the length
    
    input:
      EgoData:
        enabled: True
        topic: "/carla_its_adapter/ego_data" # TODO
        rate: 100.0
      
      ObjectList:
        enabled: True
        topic: "/carla_its_adapter/object_list/base_link" # TODO
        rate: 20.0

      Route:
        enabled: True
        topic: "/global_planner/local/route"
        rate: 20.0

      DriveableSpace:
        enabled: True
        topic: "/global_planner/local/driveable_space"
        rate: 20.0
