services:

  perception.lanelet2-object-list-filter:
      extends:
        file: ../../docker-compose-essentials/docker-compose.template.yml
        service: ros2-service
      image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/perception/lanelet2_object_list_filter:latest_initial-development_ci-amd64
      environment:
        NAMESPACE: /perception
        NAME: lanelet2_object_list_filter
        USE_SIM_TIME: ${USE_SIM_TIME:-false}
        # inputs
        INPUT_TOPIC: /perception/point_cloud_object_detection/object_list
        # outputs
        OUTPUT_TOPIC: /perception/point_cloud_object_detection/object_list/filtered
      command:
        - /bin/bash
        - -ic
        - |
          ros2 launch lanelet2_object_list_filter lanelet2_object_list_filter.launch.py \
            namespace:=$${NAMESPACE} \
            name:=$${NAME} \
            use_sim_time:=$${USE_SIM_TIME} \
            input_topic:=$${INPUT_TOPIC} \
            output_topic:=$${OUTPUT_TOPIC}
      # volumes:
      #   - ./params.yml:/docker-ros/ws/install/lanelet2_object_list_filter/share/lanelet2_object_list_filter/config/params.yml
