# === Environment Variables ====================================================
# - PARAMS_YML
# - OL_INPUT_TOPIC
# ==============================================================================

services:

  environment-interpreation.lanelet2-object-list-prediction:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/understanding/lanelet2_object_list_prediction:latest
    command: ros2 launch object_list_prediction object_list_prediction_node_launch.py input_topic:=${OL_INPUT_TOPIC}
    volumes:
      - ${PARAMS_YML:-./config/params.yml}:/docker-ros/ws/install/lanelet2_object_list_prediction/share/lanelet2_object_list_prediction/config/params.yml