# Remote compose file with overrides defined here can be rendered by
# `../../utils/scripts/render_compose_sources.py`

include:
  # https://github.com/thinking-cars/autoware_multi_object_tracker/blob/v1.1.0/docker/compose/docker-compose.yml
  - oci://ghcr.io/thinking-cars/autoware_multi_object_tracker:compose-v1.1.0

services:

  autoware-multi-object-tracker:
    extends:
      file: ../../utils/compose/docker-compose.template.yml
      service: ros2-service
    environment:
      # --- name ------
      NAMESPACE: /understanding
      # --- inputs ----
      INPUT_DETECTION01_OBJECTS: /perception/point_cloud_object_detection/object_list
      INPUT_DETECTION01_CHANNEL: untracked_objects
      OUTPUT_OBJECTS: ~/object_list
      OUTPUT_MERGED_OBJECTS: ~/merged_object_list
