# === Environment Variables ================
# - ODOMETRY_TOPIC      (required)
# - NAV_SAT_FIX_TOPIC   (optional)
# - IMU_ACC_TOPIC       (optional)
# - VEHICLE_STATE_TOPIC (optional)
# - TRAJECTORY_TOPIC    (optional)
# - EGO_DATA_TOPIC      (optional)
# - USE_SIM_TIME        (optional)
# - PARAMS_YML          (required)
# ==========================================

services:

  localization.ego-state-estimation:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/localization/ego_state_estimation:latest_improvements_ci
    command: ros2 launch ego_state_estimation ego_state_estimation_node.launch.py nav_sat_fix_topic:=${NAV_SAT_FIX_TOPIC} odometry_topic:=${ODOMETRY_TOPIC:-~/odometry} imu_acc_topic:=${IMU_ACC_TOPIC:-~/imu_acc} vehicle_state_topic:=${VEHICLE_STATE_TOPIC:-~/vehicle_state} trajectory_topic:=${TRAJECTORY_TOPIC:-/planning/drivable_trajectory} ego_data_topic:=${EGO_DATA_TOPIC:-/localization/ego_data}
    volumes:
      - ${PARAMS_YML}:/docker-ros/ws/install/ego_state_estimation/share/ego_state_estimation/config/params.yml

