services:

  localization.ego-state-estimation:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/localization/ego_state_estimation:v1.1.0
    environment:
      NAMESPACE: /localization
      NAME: ego_state_estimation
      USE_SIM_TIME: ${USE_SIM_TIME:-false}
      # inputs
      IMU_ACC_TOPIC: ~/imu_acc
      NAV_SAT_FIX_TOPIC: ~/nav_sat_fix
      ODOMETRY_TOPIC: ~/odometry
      SBG_ROT_ACCEL_TOPIC: ~/sbg_rot_accel
      SBG_VEL_TOPIC: ~/sbg_vel
      TRAJECTORY_TOPIC: /planning/trajectory_optimization/drivable_trajectory
      VEHICLE_STATE_TOPIC: ~/vehicle_state
      # outputs
      EGO_DATA_TOPIC: ~/ego_data
      EGO_DATA_NAV_SAT_FIX_TOPIC: ~/nav_sat_fix
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch ego_state_estimation ego_state_estimation_node.launch.py \
          namespace:=$${NAMESPACE} \
          name:=$${NAME} \
          use_sim_time:=$${USE_SIM_TIME} \
          imu_acc_topic:=$${IMU_ACC_TOPIC} \
          nav_sat_fix_topic:=$${NAV_SAT_FIX_TOPIC} \
          odometry_topic:=$${ODOMETRY_TOPIC} \
          sbg_rot_accel_topic:=$${SBG_ROT_ACCEL_TOPIC} \
          sbg_vel_topic:=$${SBG_VEL_TOPIC} \
          trajectory_topic:=$${TRAJECTORY_TOPIC} \
          vehicle_state_topic:=$${VEHICLE_STATE_TOPIC} \
          ego_data_topic:=$${EGO_DATA_TOPIC} \
          ego_data_nav_sat_fix_topic:=$${EGO_DATA_NAV_SAT_FIX_TOPIC}
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/ego_state_estimation/share/ego_state_estimation/config/params.yml
