services:

  perception.point-cloud-fusion:
      extends:
        file: ../../docker-compose-essentials/docker-compose.template.yml
        service: ros2-service
      image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/perception/point_cloud_fusion:v1.0.0
      environment:
        NAMESPACE: /perception
        NAME: point_cloud_fusion
        USE_SIM_TIME: false
        ROS_TRACING: false
        OUTPUT_TOPIC: ~/points
      command:
        - /bin/bash
        - -ic
        - |
          ros2 launch point_cloud_fusion point_cloud_fusion.launch.py \
            namespace:=$${NAMESPACE} \
            name:=$${NAME} \
            use_sim_time:=$${USE_SIM_TIME} \
            trace:=$${ROS_TRACING} \
            output_topic:=$${OUTPUT_TOPIC}
      # volumes:
      #   - ./params.yml:/docker-ros/ws/install/point_cloud_fusion/share/point_cloud_fusion/config/params.yml
