services:

  perception.point-cloud-fusion:
      extends:
        file: ../../docker-compose-essentials/docker-compose.template.yml
        service: ros2-service
      image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/perception/point_cloud_fusion:latest
      environment:
        NAMESPACE: /perception
        NAME: point_cloud_fusion
        USE_SIM_TIME: false
        INPUT_TOPIC_1: ~/input1
        INPUT_TOPIC_2: ~/input2
        OUTPUT_TOPIC: ~/output
      command:
        - /bin/bash
        - -c
        - |
          ros2 launch point_cloud_fusion point_cloud_fusion.launch.py \
            namespace:=$${NAMESPACE} \
            name:=$${NAME} \
            use_sim_time:=$${USE_SIM_TIME} \
            input_topic1:=$${INPUT_TOPIC_1} \
            input_topic2:=$${INPUT_TOPIC_2} \
            output_topic:=$${OUTPUT_TOPIC}
      # volumes:
      #   - ./params.yml:/docker-ros/ws/install/point_cloud_fusion/share/point_cloud_fusion/config/params.yml
