services:

  monitoring.bag-replay:
    extends:
      file: ../../utils/compose/docker-compose.template.yml
      service: ros2-service
    image: ghcr.io/openads-project/openadstack/demo-data:v1.0.0
    restart: unless-stopped
    command:
      - /bin/bash
      - -ic
      - |

        (
          for _ in $(seq 1 30); do
            if ros2 action list | grep -q '^/planning/lanelet2_route_planning/plan_route$'; then
              break
            fi
            sleep 1
          done

          ros2 action send_goal \
            /planning/lanelet2_route_planning/plan_route \
            route_planning_msgs/action/PlanRoute \
            "{
              destination: {
                header: {frame_id: 'map'},
                point: {
                  x: 303.0938415527344,
                  y: 235.60919189453125,
                  z: 0.03127288818359375
                }
              },
              intermediate_destinations: [
                {
                  header: {frame_id: 'map'},
                  point: {
                    x: 247.24014282226562,
                    y: 59.348243713378906,
                    z: 1.3430328369140625
                  }
                }
              ]
            }" \
            --feedback || true
        ) &

        ros2 bag play --start-offset 20 --playback-duration 220 --input /data --clock --regex "/drivers.*|/localization/ego_state_estimation.*|/perception/point_cloud_object_detection_ouster/object_list|/tf.*"

  monitoring.topic-relay:
    extends:
      file: ../../utils/compose/docker-compose.template.yml
      service: ros2-service
    image: ghcr.io/openads-project/monitoring:v1.0.0
    command:
      - /bin/bash
      - -ic
      - |
        ros2 run topic_tools relay /perception/point_cloud_object_detection_ouster/object_list /perception/point_cloud_object_detection/object_list

  # workaround to avoid aerial map display z-offset
  monitoring.aerial-map-workaround:
    extends:
      file: ../../utils/compose/docker-compose.template.yml
      service: ros2-service
    image: ghcr.io/openads-project/monitoring:v1.0.0
    restart: unless-stopped # requires incoming topic
    command:
      - /bin/bash
      - -ic
      - |
        ros2 run tf2_ros static_transform_publisher \
          --frame-id base_link \
          --child-frame-id aerial_map_display_link \
          --z 1.0 \
          --ros-args -p use_sim_time:=true &

        exec ros2 run topic_tools transform \
          /localization/ego_state_estimation/nav_sat_fix /aerial_map/nav_sat_fix sensor_msgs/msg/NavSatFix \
          "setattr(m.header, 'frame_id', 'aerial_map_display_link') or m" \
          --import sensor_msgs \
          --ros-args -p use_sim_time:=true
