services:

  control.automated-emergency-braking:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/control/automated_emergency_braking:latest
    environment:
      NAMESPACE: /control
      NAME: automated_emergency_braking
      OCCUPANCY_GRID_TOPIC: /perception/point_cloud_grid_mapping/occupancy_grid
      EGO_DATA_TOPIC: /localization/ego_data
      EMERGENCY_STOP_SERVICE: /dbw_supervisor/emergency_stop
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch automated_emergency_braking automated_emergency_braking_launch.py \
          namespace:=$${NAMESPACE} \
          name:=$${NAME} \
          occupancy_grid_topic:=$${OCCUPANCY_GRID_TOPIC} \
          ego_data_topic:=$${EGO_DATA_TOPIC} \
          emergency_stop_service:=$${EMERGENCY_STOP_SERVICE}
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/automated_emergency_braking/share/automated_emergency_braking/config/params.yml
