# === Environment Variables ====================================================
# - EGO_DATA_TOPIC
# - ROUTE_TOPIC
# - TRAFFIC_LIGHT_TOPIC
# - ENRICHED_ROUTE_TOPIC
# - USE_SIM_TIME
# - PARAMS_YML
# ==============================================================================

services:

  environment-interpretation.dynamic-map-enrichment:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/understanding/dynamic_map_enrichment:latest
    command: ros2 launch dynamic_map_enrichment dynamic_map_enrichment_node.launch.py ego_data_topic:=${EGO_DATA_TOPIC} route_topic:=${ROUTE_TOPIC:-/route_planning/route} traffic_light_topic:=${TRAFFIC_LIGHT_TOPIC:-/traffic_light_detection/tl_fusion/object_list} enriched_route_topic:=${ENRICHED_ROUTE_TOPIC:-/understanding/enriched_route} use_sim_time:=${USE_SIM_TIME:-false}
    volumes:
      - ${PARAMS_YML:-./config/params.yml}:/docker-ros/ws/install/dynamic_map_enrichment/share/dynamic_map_enrichment/config/params.yml
