services:

  communication.etsi-its-mcm-bridge:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/communication/etsi_its_mcm_bridge:latest
    environment:
      NAMESPACE: /communication
      NAME: etsi_its_mcm_bridge
      EGO_DATA_TOPIC: /localization/ego_data
      ROUTE_TOPIC: /lanelet2_route_planning/route
      MCM_TRAJECTORY_TOPIC: /communication/receiver/mcm
      REFERENCE_TRAJECTORY_TOPIC: ~/reference_trajectory
      MCM_REQUEST_TOPIC: /communication/sender/mcm
      USE_SIM_TIME: false
    command:
      - /bin/bash
      - -c
      - |
        ros2 launch etsi_its_mcm_bridge etsi_its_mcm_bridge_launch.py \
          namespace:=$${NAMESPACE} \
          name:=$${NAME} \
          ego_data_topic:=$${EGO_DATA_TOPIC} \
          route_topic:=$${ROUTE_TOPIC} \
          mcm_trajectory_topic:=$${MCM_TRAJECTORY_TOPIC} \
          reference_trajectory_topic:=$${REFERENCE_TRAJECTORY_TOPIC} \
          mcm_request_topic:=$${MCM_REQUEST_TOPIC} \
          use_sim_time:=$${USE_SIM_TIME}
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/etsi_its_mcm_bridge/share/etsi_its_mcm_bridge/config/params.yml
