#!/usr/bin/env python3
"""Render Docker Compose files by resolving OCI image references in `include` directives."""

import argparse
import copy
import io
import os
import shutil
import sys
import tempfile
from pathlib import Path
from typing import Any

from oras.client import OrasClient
from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap, CommentedSeq

YAML_RT = YAML()
YAML_RT.preserve_quotes = True
YAML_RT.width = 4096
YAML_RT.indent(mapping=2, sequence=4, offset=2)
PROJECT_ROOT = Path(__file__).resolve().parent.parent


def oci_compose(client: OrasClient, uri: str) -> CommentedMap:
    target = uri.removeprefix("oci://")
    with tempfile.TemporaryDirectory() as outdir:
        for path in client.pull(target, outdir=outdir):
            document = load_yaml(Path(path))
            if any(key in document for key in ("services", "include", "networks", "volumes")):
                return document
    raise RuntimeError(f"no compose YAML layer found in {uri}")


def load_yaml(source: str | Path) -> CommentedMap:
    text = source.read_text() if isinstance(source, Path) else source
    document = YAML_RT.load(text) or CommentedMap()
    if not isinstance(document, CommentedMap):
        raise ValueError("compose YAML must be a mapping")
    return document


def render_compose(source: Path, destination: Path, client: OrasClient) -> str:
    local = load_yaml(source)
    includes = include_list(local.get("include"))
    rendered = CommentedMap()
    for include in includes:
        if is_oci(include):
            rendered = merge(rendered, oci_compose(client, include))
    local = copy.copy(local)
    remaining = [include for include in includes if not is_oci(include)]
    if remaining:
        local["include"] = remaining[0] if len(remaining) == 1 else CommentedSeq(remaining)
    else:
        local.pop("include", None)
        local.ca.items.pop("include", None)
    buffer = io.StringIO()
    buffer.write(generated_header(source, destination))
    YAML_RT.dump(merge(rendered, local), buffer)
    return buffer.getvalue()


def include_list(value: Any) -> list[Any]:
    if value is None:
        return []
    return list(value) if isinstance(value, list) else [value]


def is_oci(value: Any) -> bool:
    return isinstance(value, str) and value.startswith("oci://")


def merge(base: Any, override: Any) -> Any:
    if isinstance(base, CommentedMap) and isinstance(override, CommentedMap):
        for key, value in override.items():
            if key in base:
                base[key] = merge(base[key], value)
            else:
                base[key] = value
                if key in override.ca.items:
                    base.ca.items[key] = override.ca.items[key]
        return base
    return override


def generated_header(source: Path, destination: Path) -> str:
    parent = destination.resolve().parent
    script = os.path.relpath(Path(__file__).resolve(), parent)
    source_path = os.path.relpath(source.resolve(), parent)
    return f"# Auto-generated by `{script}` based on\n#   {source_path}\n\n"


def relative_path(path: Path) -> str:
    return os.path.relpath(path.resolve(), Path.cwd())


def render_files(sources_dir: Path, output_dir: Path, dry_run: bool) -> None:
    client = OrasClient()
    for source in sorted(path for path in sources_dir.rglob("*") if path.is_file()):
        destination = output_dir / source.relative_to(sources_dir)
        action = "rendering" if source.name == "docker-compose.yml" else "copying"
        print(f"{action} {relative_path(source)} -> {relative_path(destination)}")
        if dry_run:
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        if source.name == "docker-compose.yml":
            destination.write_text(render_compose(source, destination, client))
        else:
            shutil.copy2(source, destination)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sources-dir", type=Path, default=PROJECT_ROOT / "compose-sources")
    parser.add_argument("--output-dir", type=Path, default=PROJECT_ROOT / "compose")
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    sources_dir = args.sources_dir.resolve()
    if not sources_dir.is_dir():
        print(f"error: sources directory does not exist: {sources_dir}", file=sys.stderr)
        return 2
    render_files(sources_dir, args.output_dir.resolve(), args.dry_run)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
