services:

  trace-compass:
    extends:
      file: ../docker-compose-essentials/docker-compose.template.yml
      service: ros2-x11-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/misc/ros2_tracing:latest-dev_trace-compass_ci
    command: bash -ic "cd /trace && tracecompass"
    volumes:
      - .:/trace
    ports:
      - 8888:8888
