# === Environment Variables ====================================================
# - PARAMS_YML  (required)
# ==============================================================================

services:

  communication.mqtt-client-interfaces:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/communication/mqtt-client-interfaces:latest
    command: ros2 launch mqtt_client standalone.launch.xml params_file:=/params.yml
    volumes:
      - ${PARAMS_YML:-/dev/null:/dev/null}${PARAMS_YML:+:/params.yml}
