services:

  communication.mqtt-client:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/communication/mqtt-client-interfaces:latest
    environment:
      NAMESPACE: /communication
      NAME: mqtt_client
    command:
      - /bin/bash
      - -c
      - |
        ros2 launch mqtt_client standalone.launch.xml \
          namespace:=${NAMESPACE} \
          node_name:=${NAME}
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/mqtt_client/share/mqtt_client/config/params.yaml
