services:

  understanding.lanelet2-object-list-prediction:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/understanding/lanelet2_object_list_prediction:latest
    environment:
      NAMESPACE: /understanding
      NAME: lanelet2_object_list_prediction
      USE_SIM_TIME: ${USE_SIM_TIME:-false}
      ROS_TRACING: ${ROS_TRACING:-false}
      # inputs
      OBJECT_LIST_TOPIC: /understanding/simple_object_tracking/object_list
      # outputs
      PREDICTED_OBJECT_LIST_TOPIC: ~/predicted_object_list
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch lanelet2_object_list_prediction object_list_prediction_node_launch.py \
          namespace:=$${NAMESPACE} \
          name:=$${NAME} \
          use_sim_time:=$${USE_SIM_TIME} \
          trace:=$${ROS_TRACING} \
          object_list_topic:=$${OBJECT_LIST_TOPIC} \
          predicted_object_list_topic:=$${PREDICTED_OBJECT_LIST_TOPIC}
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/lanelet2_object_list_prediction/share/lanelet2_object_list_prediction/config/params.yml
