services:

  understanding.lanelet2-object-list-prediction:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/understanding/lanelet2_object_list_prediction:v1.0.0
    environment:
      NAMESPACE: /understanding
      NAME: lanelet2_object_list_prediction
      USE_SIM_TIME: false
      INPUT_TOPIC: /understanding/fused_object_list
      OUTPUT_TOPIC: /understanding/predicted_object_list
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch lanelet2_object_list_prediction object_list_prediction_node_launch.py \
          namespace:=$${NAMESPACE} \
          name:=$${NAME} \
          use_sim_time:=$${USE_SIM_TIME} \
          input_topic:=$${INPUT_TOPIC} \
          output_topic:=$${OUTPUT_TOPIC}
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/lanelet2_object_list_prediction/share/lanelet2_object_list_prediction/config/params.yml
