include:
  - ./docker-compose.openadstack.yml
  - ./utils/docker-compose.yml

services:

  point-cloud-fusion:
    profiles:
      - do-not-use

  point-cloud-object-detection:
    profiles:
      - do-not-use