include:

  # essentials
  - ../essentials/zenoh-router/docker-compose.yml

  # localization
  - ../localization/lanelet2_map_server/docker-compose.yml

  # understanding
  - ../understanding/autoware_multi_object_tracker/docker-compose.yml
  - ../understanding/simple_object_tracking/docker-compose.yml
  - ../understanding/lanelet2_object_list_prediction/docker-compose.yml
  
  # planning
  - ../planning/lanelet2_route_planning/docker-compose.yml
  - ../planning/simple_planner/docker-compose.yml
  - ../planning/trajectory_optimization/docker-compose.yml

  # control
  - ../control/ackermann_trajectory_control/docker-compose.yml

  # monitoring
  - ../monitoring/monitoring/docker-compose.yml

  # bag replay
  - ./bag-replay/docker-compose.yml

# Demo overrides
services:

  monitoring:
    environment: 
      USE_SIM_TIME: true
    volumes:
      - ./rviz/conf.rviz:/conf.rviz
      - ./rviz/mesh:/mesh

  robot-state-publisher:
    extends:
      file: ../utils/compose/docker-compose.template.yml
      service: ros2-service
    image: ghcr.io/openads-project/monitoring:v1.0.0
    command: ros2 run robot_state_publisher robot_state_publisher /urdf/karl.urdf
    volumes:
      - ./rviz/urdf:/urdf

  lanelet2-map-server:
    environment:
      USE_SIM_TIME: true
    volumes:
      - ./lanelet2_map_server/params.yml:/params.yml
      - ./lanelet2_map_server/maps:/data/maps

  autoware-multi-object-tracker:
    environment:
      USE_SIM_TIME: true
      PARAMS: /docker-ros/ws/install/autoware_multi_object_tracker/share/autoware_multi_object_tracker/config/multi_object_tracker_node.param.yaml

  simple-object-tracking:
    environment:
      USE_SIM_TIME: true
      PARAMS: /docker-ros/ws/install/simple_object_tracking/share/simple_object_tracking/config/params.yml

  lanelet2-object-list-prediction:
    environment:
      USE_SIM_TIME: true
      PARAMS: /docker-ros/ws/install/lanelet2_object_list_prediction/share/lanelet2_object_list_prediction/config/params.yml

  lanelet2-route-planning:
    environment:
      USE_SIM_TIME: true
      PARAMS: /docker-ros/ws/install/lanelet2_route_planning/share/lanelet2_route_planning/config/params.yml

  simple-planner:
    environment:
      USE_SIM_TIME: true
      PARAMS: /docker-ros/ws/install/simple_planner/share/simple_planner/config/params.yml

  trajectory-optimization:
    environment:
      USE_SIM_TIME: true
      PARAMS: /docker-ros/ws/install/trajectory_optimization/share/trajectory_optimization/config/params.yml

  ackermann-trajectory-control:
    environment:
      USE_SIM_TIME: true
      PARAMS: /docker-ros/ws/install/ackermann_trajectory_control/share/ackermann_trajectory_control/config/params.yml