include:
  - ./docker-compose.openadstack.yml
  - ./utils/docker-compose.yml

services:
  
  demo.bag-replay:
    image: ghcr.io/openads-project/openadstack/demo-data:basic_v1.0.0
  
  point-cloud-fusion:
    profiles:
      - do-not-use

  point-cloud-object-detection:
    profiles:
      - do-not-use