include:
  - ./docker-compose.openadstack.yml
  - ./utils/docker-compose.yml

services:

  point-cloud-fusion:
    profiles:
      - do-not-use

  point-cloud-object-detection:
    profiles:
      - do-not-use

  lanelet2-map-server:
    volumes:
      - ./lanelet2_map_server/params.yml:/docker-ros/ws/install/lanelet2_map_server/share/lanelet2_map_server/config/params.yml
      - ./lanelet2_map_server/maps:/data/maps

  monitoring:
    volumes:
      - ./utils/rviz/conf.rviz:/conf.rviz
      - ./utils/mesh:/mesh
