include:
  - ./docker-compose.openadstack.yml
  - ./utils/docker-compose.yml

services:

  demo.bag-replay:
    image: ghcr.io/openads-project/openadstack/data-demo-extended:v1.0.0
    # image: ghcr.io/openads-project/openadstack/data-demo-full:v1.0.0

  demo.topic-relay:
    profiles:
      - do-not-use

  point-cloud-fusion:
    volumes:
      - ./point_cloud_fusion/params.yml:/docker-ros/ws/install/point_cloud_fusion/share/point_cloud_fusion/config/params.yml

  point-cloud-object-detection:
    volumes:
      - ./point_cloud_object_detection/params.yml:/docker-ros/ws/install/point_cloud_object_detection/share/point_cloud_object_detection/config/params.yml
      - perception.point-cloud-object-detection-model:/models/point-cloud-object-detection:ro

  triton-server:
    extends:
      file: ../essentials/triton-server/docker-compose.yml
      service: triton-server
    depends_on:
      - perception.point-cloud-object-detection-model-provisioning
    volumes:
      - perception.point-cloud-object-detection-model:/models/point-cloud-object-detection:ro

  perception.point-cloud-object-detection-model-provisioning:
    image: ghcr.io/openads-project/point_cloud_object_detection/model:v3.0.0
    command: sleep infinity
    volumes:
      - perception.point-cloud-object-detection-model:/model

volumes:
  perception.point-cloud-object-detection-model:
