services:

  orchestration.event-action-orchestration:
      extends:
        file: ../../docker-compose-essentials/docker-compose.template.yml
        service: ros2-service
      image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/orchestration/event_action_orchestration:v1.0.0
      environment:
        NAMESPACE: /orchestration
        NAME: event_action_orchestration
        USE_SIM_TIME: ${USE_SIM_TIME:-false}
      command:
        - /bin/bash
        - -ic
        - |
          ros2 launch event_action_orchestration event_action_orchestration_launch.py \
            namespace:=$${NAMESPACE} \
            name:=$${NAME} \
            use_sim_time:=$${USE_SIM_TIME}
      # volumes:
      #   - ./params.yml:/docker-ros/ws/install/event_action_orchestration/share/event_action_orchestration/config/params.yml
