services:

  zenoh-router:
    extends:
      file: ../docker-compose-essentials/docker-compose.template.yml
      service: zenoh-router

include:
  - ./planning/lanelet2_route_planning/docker-compose.yml
  - ./planning/trajectory_optimization/docker-compose.yml
