services:

  localization.lanelet2-map-server:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/localization/lanelet2_map_server:v1.1.1
    environment:
      NAMESPACE: /localization
      NAME: lanelet2_map_server
      USE_SIM_TIME: false
      MAP_FRAME_ID: map
      NAV_SAT_FIX_TOPIC: /localization/nav_sat_fix
      USE_AUTOMATIC_MAP_SELECTION: false
      MAP_DIRECTORY: /data/maps/default-maps
      MAP_FILEPATH: /data/maps/aachen.osm
      ORIGIN_LAT:
      ORIGIN_LON:
    command:
      - /bin/bash
      - -ic
      - |
        ros2 run lanelet2_map_server lanelet2_map_server --ros-args \
          -r __ns:=$${NAMESPACE} \
          -r __node:=$${NAME} \
          -r $${NAMESPACE}/$${NAME}/gps/fix:=$${NAV_SAT_FIX_TOPIC} \
          -p use_sim_time:=$${USE_SIM_TIME} \
          -p map_frame_id:=$${MAP_FRAME_ID} \
          -p use_automatic_map_selection:=$${USE_AUTOMATIC_MAP_SELECTION} \
          -p map_directory:=$${MAP_DIRECTORY} \
          -p map_filepath:=$${MAP_FILEPATH} \
          $${ORIGIN_LAT:+-p origin_lat:=$${ORIGIN_LAT}} \
          $${ORIGIN_LON:+-p origin_lon:=$${ORIGIN_LON}}
