services:

  localization.lanelet2-map-server:
    extends:
      file: ../../docker-compose-essentials/docker-compose.template.yml
      service: ros2-service
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/localization/lanelet2_map_server:latest
    environment:
      NAMESPACE: /localization
      NAME: lanelet2_map_server
      USE_SIM_TIME: false
      MAP_FRAME_ID: map
      MAP_FILEPATH: /data/maps/locations/germany-aldenhoven-atc/lanelet2/ika-carla/ATC.osm
      ORIGIN_LAT: 50.908973
      ORIGIN_LON: 6.230061
      # MAP_FILEPATH: /data/maps/locations/germany-aachen-campusmelaten/lanelet2/ika-testtrack/ika-testtrack-autoshuttle.osm
      # ORIGIN_LAT: 50.787047
      # ORIGIN_LON: 6.046511
      # MAP_FILEPATH: /data/maps/locations/germany-aachen-campusmelaten/lanelet2/ika-campus-vaals-halifax/CampusVaalsHalifax.osm
      # ORIGIN_LAT: 50.787047
      # ORIGIN_LON: 6.046511
      # MAP_FILEPATH: /data/maps/locations/synthetic-carla/lanelet2/town10hd/Town10HD.osm
      # ORIGIN_LAT: 0.0
      # ORIGIN_LON: 0.0
    command:
      - /bin/bash
      - -ic
      - |
        ros2 run lanelet2_map_server lanelet2_map_server --ros-args \
          -r __ns:=$${NAMESPACE} \
          -r __node:=$${NAME} \
          -p use_sim_time:=$${USE_SIM_TIME} \
          -p map_frame_id:=$${MAP_FRAME_ID} \
          -p map_filepath:=$${MAP_FILEPATH} \
          -p origin_lat:=$${ORIGIN_LAT} \
          -p origin_lon:=$${ORIGIN_LON}
