# === Environment Variables ====================================================
# - CONFIG_JSON
# ==============================================================================

services:

  communication.zenoh-router:
    image: eclipse/zenoh:0.11.0
    ports:
      - 7447:7447

  communication.zenoh-bridge:
    image: eclipse/zenoh-bridge-ros2dds:0.11.0
    restart: unless-stopped
    depends_on:
      - communication.zenoh-router
    command: -c /config.json5
    environment:
      ROS_DISTRO: humble
    volumes:
      - ${CONFIG_JSON:-./config/config.json5}:/config.json5
