# === Environment Variables ====================================================
# - CONFIG_JSON (required)
# ==============================================================================

services:

  communication.zenoh-router:
    image: eclipse/zenoh:1.0.0
    restart: unless-stopped
    ports:
      - 7447:7447

  communication.zenoh-bridge:
    image: eclipse/zenoh-bridge-ros2dds:1.0.0
    restart: unless-stopped
    command: -c /config.json5
    environment:
      ROS_DISTRO: humble
    volumes:
      - ${CONFIG_JSON:-/dev/null:/dev/null}${CONFIG_JSON:+:/config.json5}
